#Problem
#Given: A DNA string s of length at most 1000 nt.
#Return: Four integers (separated by spaces) counting the respective number of times that the 
#symbols 'A', 'C', 'G', and 'T' occur in s.

s= "GGGACTCAATTCTCATGGGCTTGTACGCGGCGGATGCTTAGACTCATGCCATCGGTTATCTTGCGAACACAGCAGTGCGACATACTCCTACCCTACTAGGCCTTAGCTGCAGTTGGTTAGCAGCCGTACCGGCTATGCTAGGTAGTGTTCAATAGCGGGGCTGCAAGCTCTCATAGCGACGAGAGGGCTTATCCCCTGTATTTCGGTTCAATCGGAGCTGCCGGTTTTTAGGCTACTAGCATGCAGACTGAGGCGTACTAAATGGCTTCCATACCATACTCCCCGTCACAGGTGCTAGTGTATCGATGGTATACTTCAGGAAATGGGTGCGGTGGTTACAAATTCAAGCTGGCGCACTGCGCATCGTAGTAATGTTGCGGTGGGCTAGATGACTCCGCTGGTCCTCGATATTGAGGTATGCAGGCAAGGATCACGGCAAATTAGGCTCTCTGTGGCTCAAACGGACCATAGTTCTTCCGGAACACAAGGGGTTACAGGAACACATCTGCCTACGAGCTGCCGGCGGTACCTTCTCTACTTAGAGGAGATTGTGTCCAATGAGTTGGTTTTTTTCATAGCTGCCGGAATATGAGAAATGCGCTCGGTCAATGCGTTCATCAAGCGTCGATTCGCTAGTATATATGAGGAGGACATAAATAGCGATGGGTTGGGTTCATAGGATTTGTTGTTGAATTGATGCAGATAGTTAGGAACTACGCCTAGAGGGTAGATCGAACAATTGAGAGTGATCACCCTGAGCATTCGATGGTGGTCGTTCGAATCATTGTCTCTTAAGCCGAACATACCTGCGCTGCTGTGCAAAGTTGCTGCTTGCCGCCGCGATTAAGTTGGGATAACAGGCGGACCGTGGAATATATATGATGTGTCTACTACTGTCCACCGCATGGATCGTTGGAATGCTCCCGACAACCTCA"
counter1 = 0
counter2 = 0
counter3 = 0
counter4 = 0

for letter in s:
    if letter == "A":
        counter1+=1 
    elif letter == "C":
        counter2+=1
    elif letter == "G":
        counter3+=1
    elif letter == "T":
        counter4+=1
print(counter1, counter2, counter3, counter4)
